# This workflow will install Python dependencies, run build tests and checks with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Setup

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python 2.7
      uses: actions/setup-python@v2.1.1
      with:
        python-version: 2.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine check-manifest

    - name: Show versions
      run: |
        python --version
        pip --version
        twine --version
        wheel version

    - name: Build and check with twine
      run: |
        check-manifest
        python setup.py check --metadata --strict
        python setup.py build
        python setup.py test
        python setup.py sdist bdist_wheel
        twine check dist/*
