# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 2.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=tests
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --exclude=tests

    - name: Test spunky.py with Pylint
      run: |
        pip install pylint
        pylint spunky.py --disable=C0103,C0111,C0301,C0302,W0703,R0101,R0201,R0902,R0903,R0904,R0912,R0913,R0914,R0915,R0916

    # make sure that the README is formatted properly
    - name: Lint format in setup.py
      run: python setup.py check --restructuredtext --strict --metadata

    - name: Lint with RST reStructuredText
      run: rst-lint README.md CHANGELOG.md LICENSE doc/Commands.md .github/CONTRIBUTING.md .github/CODE_OF_CONDUCT.md .github/SUPPORT.md
